### ISSUE TITLE
PVD 5th unused field check too strict

### ISSUE THREAD

**Issue by DarkPlayer** [clalancette/pycdlib#1]
I was playing around with pycdlib to decide whether I should use it in one of my projects and discovered that it fails to load an iso9960 file with joliet level 3. The iso in question is the Tribes Vengeance CD1 iso. You can download it from https://www.tribesuniverse.com/ ([direct download link](http://lwcdn.hi-rezgame.net/media/iso/TribesVengeance.zip)).

Just extract the zip and try to load `Tribes Vengeance 1of4.iso` using pycdlib. This will result in the following exception:

```
pycdlib/headervd.py in parse(self, vd, data_fp, extent_loc)
    549         # According to Ecma-119, the last 653 bytes of the PVD should be all 0.
    550         if unused5 != b'\x00'*653:
--> 551             raise pycdlibexception.PyCdlibException("data in 5th unused field not zero")
    552 
    553         # Check to make sure that the little-endian and big-endian versions

PyCdlibException: data in 5th unused field not zero
```
PS: Is there any interest in having python3 support?

**Comment by clalancette** [comment]
Cool!  That's awesome that you've decided to take a look at it.  Thanks for the feedback; I'll download that ISO and see if I can figure out what is wrong with it.

It's funny that you mention python3 support.  I've just been working on that in the last couple of weeks.  I have it mostly working now, I just have a few more things to finish up and then it should be done.  I'll definitely let you know when I've fixed these problems.

**Comment by clalancette** [comment]
All right, I've relaxed that particular requirement.  A quick check with the pycdlib-explorer looks like that particular ISO basically works.  Try it out on master and let me know if it works for you, or if you have further issues or questions.  I'll be landing the python3 support in the next few days.

**Comment by DarkPlayer** [comment]
I just verified that it works with 9c2fffb522c755a6ab1e097b8831dd18d314ea17. Thanks for fixing this so quickly.

**Comment by clalancette** [comment]
Just FYI, I landed Python3 support tonight.  I've only given it light testing so far, but it seems to work.  I did have to change around some of the ways I did things so that things would work, including paths.  Let me know if you get a chance to test it and if it works for you.
