### ISSUE TITLE
Python 3.4 compatibility? 

### ISSUE THREAD

**Issue by clebergnu** [clalancette/pycdlib#12]
Hi,

`setup.py` advertises Python 3.4 compatiblity (https://github.com/clalancette/pycdlib/blob/master/setup.py#L51), but I've found code that uses constructs from 3.6+.  One example is `ModuleNotFoundError`:

https://github.com/clalancette/pycdlib/blob/master/pycdlib/utils.py#L25

Our tests catching those failures can be seen here:

https://travis-ci.org/avocado-framework/avocado/jobs/407295747#L1699

**Comment by clalancette** [comment]
Hi there,
     Thanks for the bug report!  Up to this point, I've only really tested pycdlib on Python 3.6; the 3.4 is a holdover from when I copied that bit of setup.py from another project.  I could go one of two ways on this:

1.  Keep the Python 3.4 designation in setup.py, and fix the offending code (I doubt there will be a lot, so it should be pretty straightforward).
1.  Change setup.py to Python 3.6, since I know that works, and I regularly test it.

Do you have a preference which way I go?

**Comment by clebergnu** [comment]
I'd say that, if the offending code is not that much (and you are right, it
doesn't look to be much), I'd keep it 3.4 compatible.

Also, if you like, I may be able to help with Travis CI to run tests on all
those Python versions.

Regards.

**Comment by clalancette** [comment]
> I'd say that, if the offending code is not that much (and you are right, it doesn't look to be much), I'd keep it 3.4 compatible. 

Makes sense.  Try out the latest master of pycdlib; Python 3.4 worked in my testing there.

> Also, if you like, I may be able to help with Travis CI to run tests on all those Python versions.

That would be fantastic if you have time.  My biggest concern with the Python 3.4 compatibility is that I'll inadvertently break it in the future since I don't test it often, so having automatic Travis tests would definitely alleviate that.  Thanks!

**Comment by clebergnu** [comment]
@clalancette I can confirm those fixes on master are enough to get Python 3.4 support.  This is a job running with the latest master:

https://travis-ci.org/avocado-framework/avocado/jobs/407593455

When can I expect a new release, so I can adjust my requirements?

Thanks.

**Comment by clalancette** [comment]
> @clalancette I can confirm those fixes on master are enough to get Python 3.4 support. This is a job running with the latest master:

Excellent, thanks for testing.

> When can I expect a new release, so I can adjust my requirements?

There's been enough work in the last month that I think it is time for another release.  I'll probably have time to get that done this coming weekend (it will be version 1.6.0).  I'm going to close this issue out; thanks again for the report and the testing.

**Comment by clalancette** [comment]
@clebergnu I did the release of 1.6.0 on Sunday, hope it works for you.

**Comment by clebergnu** [comment]
Thanks! I was away for the last few days, but I'll give it a try tomorrow.

**Comment by clebergnu** [comment]
@clalancette the new release works fine! Thanks!

**Comment by clalancette** [comment]
Fantastic, glad it is working for you.
