### ISSUE TITLE
`DirectoryRecord._add_child()` incorrectly raises a duplicate name exception

### ISSUE THREAD

**Issue by markjdb** [clalancette/pycdlib#131]
When processing the [FreeBSD 14.2-RELEASE ISO](https://download.freebsd.org/releases/ISO-IMAGES/14.2/FreeBSD-14.2-RELEASE-amd64-dvd1.iso.xz), pycdlib fails to add the entries in `usr/local/share/licenses`, which are directories with names > 33 bytes and common prefixes, e.g., `wifi-firmware-rtw88-kmod-rtw8822c-20241017_1` and `wifi-firmware-rtw88-kmod-rtw8822b-20241017_1`.

Looking at `_add_child()`, I suspect that the comparison `self.children[index].file_ident == child.file_ident` is insufficient - that compares only the embedded names, which in the case of these dirs are truncated. Should we also compare `child.rock_ridge.name()` when testing for uniqueness? Doing so fixes the problem for me; I also modified `__lt__()` to compare the full names if `file_ident` compares equal.

**Comment by markjdb** [comment]
Perhaps this is not a bug after all, and even Rock Ridge images require unique short names within a directory? It's not completely clear to me.

**Comment by markjdb** [comment]
Yes, I think this is a bug on our end. Sorry for the noise.

**Comment by emaste** [comment]
FreeBSD bug report for the makefs issue: https://bugs.freebsd.org/283238
