### ISSUE TITLE
Outdated tools & documentation

### ISSUE THREAD

**Issue by amlamarra** [clalancette/pycdlib#20]
Hey, thanks for creating this library! I'd love to use it but I'm having a hard time trying to figure it out (without reading the source code). I tried using "pycdlib-extract-files" from the "tools" directory but I get:
```
...
  File "./pycdlib-extract-files", line 79, in main
    root_entry = iso.get_record(**{pathname: args.start_path})
AttributeError: 'PyCdlib' object has no attribute 'get_record'
```

Also, I tried using extract-data.py from the "examples" directory and I get:
```
...
  File "./extract-data.py", line 36, in <module>
    iso.get_file_from_iso_fp(extracted, iso_path='/FOO.;1')
AttributeError: 'PyCdlib' object has no attribute 'get_file_from_iso_fp'
```
I looked at the documentation and it uses the same attributes as this file. Was there an update to the library & these examples/tools didn't get updated?

**Comment by amlamarra** [comment]
Sorry, the environment that I was in only had v1.0.0. I just did a pip3 install somewhere else & got v1.7.0. Things are now mostly working.

**Comment by clalancette** [comment]
Hi @amlamarra .

Glad you figured out your problems.  Let me know if there are other examples or documentation that would help you to get started.  I've tried to present what I thought was useful at https://clalancette.github.io/pycdlib/ and https://github.com/clalancette/pycdlib/tree/master/examples , but we can always improve things.

**Comment by amlamarra** [comment]
If I'm having issues with pycdlib-extract-files.py, should I open another issue here? For instance, I'm unable to extract Windows ISOs. It gives me `pycdlib.pycdlibexception.PyCdlibInvalidISO: Tag version not 2 or 3`

**Comment by clalancette** [comment]
Yes, please do.  Give as much information as possible about the ISO, since the easiest way for me to debug is to get the ISO.

**Comment by amlamarra** [comment]
Ok, I'll do that. Though after more testing, it seems to only be a Windows 7 ISO that I get that message for. The other Windows ISOs just don't get extracted. Since that ISO is hard to find (Microsoft no longer offers it), I did find another ISO that gets that error.

Also, I have a few suggestions for changes to pycdlib-extract-files.py (using try-except statements & adding an '-extract-to' argument). Want me to create  pull request?
