### ISSUE TITLE
Extraction issues for certain ISOs

### ISSUE THREAD

**Issue by amlamarra** [clalancette/pycdlib#21]
I'm going to be using this library and the `pycdlib-extract-files` script to automate some ISO extraction. However, there's a few issues I wanted to address. I'm sure these issues are with the library itself & not `pycdlib-extract-files`.

First, it doesn't extract anything from certain ISOs. So far, I've only seen this issue with some Windows install ISOs. You can see for youself by getting an eval ISO of either Windows 10 or Server 2016/2019 from:
https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise
https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server

Second, I've seen it give an error on certain other ISOs. This is seen on Windows install ISOs for older versions (which are hard to find anymore) and for the latest free version of "Parted Magic" (pmagic_2013_08_01.iso), which you can get from here: https://www.majorgeeks.com/files/details/parted_magic.html
The error I get:
```
(venv) andrew ~/iso $ ./pycdlib-extract-files.py pmagic_2013_08_01.iso
Opening pmagic_2013_08_01.iso
Traceback (most recent call last):
  File "./pycdlib-extract-files.py", line 107, in <module>
    sys.exit(main())
  File "./pycdlib-extract-files.py", line 59, in main
    iso.open(args.iso)
  File "/usr/local/lib/python3.5/dist-packages/pycdlib/pycdlib.py", line 4041, in open
    self._open_fp(fp)
  File "/usr/local/lib/python3.5/dist-packages/pycdlib/pycdlib.py", line 2511, in _open_fp
    self._parse_udf_descriptors()
  File "/usr/local/lib/python3.5/dist-packages/pycdlib/pycdlib.py", line 2192, in _parse_udf_descriptors
    anchor_tag.parse(anchor_data, extent)
  File "/usr/local/lib/python3.5/dist-packages/pycdlib/udf.py", line 560, in parse
    raise pycdlibexception.PyCdlibInvalidISO('Tag version not 2 or 3')
pycdlib.pycdlibexception.PyCdlibInvalidISO: Tag version not 2 or 3
```

Third (and finally), there's just a few more miscellaneous things regarding file names. Is there a reason every file & directory name is all caps when it's extracted? Also, every file seems to have `;1` appended to the end. This one is easy enough to fix in `pycdlib-extract-files` at line 100, you can change `iso.get_file_from_iso(relname, **{pathname: ident_to_here})` to `iso.get_file_from_iso(relname[:-2], **{pathname: ident_to_here})`, though I'm not sure if this is something that should (or shouldn't) be changed in the library. Lastly, files that have no extension are given an extra period at the end (before the `;1`). This behavior can be observed using the Ubuntu 18.04.2 LTS install ISO: https://www.ubuntu.com/download/desktop
Note: I did have to modify `pycdlib-extract-files` a bit as it was halting on certain errors, like when it tried extracting empty files or symlinks:
```
Traceback (most recent call last):
  File "./pycdlib-extract-modified.py", line 111, in <module>
    sys.exit(main())
  File "./pycdlib-extract-modified.py", line 102, in main
    iso.get_file_from_iso(os.path.join(args.extract_to, relname), **{pathname: ident_to_here})
  File "/usr/local/lib/python3.5/dist-packages/pycdlib/pycdlib.py", line 4119, in get_file_from_iso
    self._get_file_from_iso_fp(fp, blocksize, iso_path, rr_path, joliet_path)
  File "/usr/local/lib/python3.5/dist-packages/pycdlib/pycdlib.py", line 2632, in _get_file_from_iso_fp
    raise pycdlibexception.PyCdlibInvalidInput('Symlinks have no data associated with them')
pycdlib.pycdlibexception.PyCdlibInvalidInput: Symlinks have no data associated with them
```
I enclosed line 100 in  a try-except statement:
```
 99         else:
100             try:
101                 iso.get_file_from_iso(os.path.join(args.extract_to, relname), **{pathname: ident_to_here})
102             except Exception as ex:
103                 print("ERROR on {}: {}".format(relname, ex.args[0]))
```
Now the output looks something like:
```
Opening /mnt/c/Users/P008261C/Downloads/ISOs/ubuntu-18.04.2-desktop-amd64.iso

.DISK
BOOT
CASPER
DISTS
EFI
INSTALL
ISOLINUX
MD5SUM.TXT;1
PICS
POOL
PRESEED
README.DISKDEFINES;1
UBUNTU.;1
ERROR on UBUNTU.;1: Symlinks have no data associated with them
.DISK/BASE_INSTALLABLE.;1
```

Thank you for your time. And just to give you an idea for the types of ISOs I mentioned here:
```
$ file Windows_10_Enterprise_EVAL_en-us.iso pmagic_2013_08_01.iso ubuntu-18.04.2-desktop-amd64.iso
Windows_10_Enterprise_EVAL_en-us.iso: ISO 9660 CD-ROM filesystem data 'CENA_X64FREE_EN-US_DV5' (bootable)
pmagic_2013_08_01.iso:                DOS/MBR boot sector ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'CDROM' (bootable); partition 1 : ID=0x17, active, start-CHS (0x0,0,1), end-CHS (0x14f,63,32), startsector 0, 688128 sectors
ubuntu-18.04.2-desktop-amd64.iso:     DOS/MBR boot sector ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'Ubuntu 18.04.2 LTS amd64' (bootable); partition 2 : ID=0xef, start-CHS (0x3ff,254,63), end-CHS (0x3ff,254,63), startsector 3830956, 4928 sectors
```

**Comment by clalancette** [comment]
@amlamarra Thanks for the detailed reports.  It looks like there are actually 3 separate issues here, so I'm going to split this into 3 separate issues and close this one out.  That way I can address them individually.  I'll post the new issue numbers here when I go to close this one out.

**Comment by clalancette** [comment]
This has been split out into #22, #23, #24, and #25.  I'm going to close this out and continue the discussion in those issues.
