### ISSUE TITLE
Certain Windows ISOs don't extract any data

### ISSUE THREAD

**Issue by clalancette** [clalancette/pycdlib#22]
@amlamarra This is the first issue split out from #21 

`pycdlib-extract-files` doesn't extract anything from certain ISOs. So far, I've only seen this issue with some Windows install ISOs. You can see for youself by getting an eval ISO of either Windows 10 or Server 2016/2019 from:
https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise
https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server

**Comment by clalancette** [comment]
This particular problem isn't a bug so much as an oddity of how Windows structures their ISOs.  Modern Windows ISOs actually have two different filesystems on it; an "original" ISO9660 filesystem, and a "UDF Bridge" filesystem.  However, the ISO9660 filesystem is empty (or only has a README file), while the UDF filesystem contains the real data.  By default, `pycdlib-extract-files` tries to extract the ISO9660 filesystem, so you'll only see the empty one.  If you run the tool like:

```
pycdlib-extract-files -udf <path/to/iso>
```

That should extract the UDF filesystem.

I know this isn't entirely user-friendly, but I'm not sure there is a better thing to do here.  *Some* ISO9660/UDF-Bridge combined filesystems have real data in both halves, so we can't know which half the user wants to extract unless they explicitly tell us.

Since this isn't a bug, I'm going to close this particular issue out, but if you have ideas on how to improve the user experience with `pycdlib-extract-files`, feel free to add a comment here.

**Comment by amlamarra** [comment]
I think I already asked this in another issue, but is there a way to automatically determine if an ISO uses ISO9660 vs UDF Bridge? I'm not asking for you to implement that in `pycdlib-extract-files` (though it would be nice). I'm asking because I'm using pycdlib to automatically extract the contents of ISOs, and it can't ask the user what type.
