### ISSUE TITLE
Filenames from pycdlib-extract-iso are in an ALLCAPS.EXT;1 style

### ISSUE THREAD

**Issue by clalancette** [clalancette/pycdlib#24]
@amlamarra This is the third issue split out of #21 

There's just a few more miscellaneous things regarding file names. Is there a reason every file & directory name is all caps when it's extracted? Also, every file seems to have `;1` appended to the end. This one is easy enough to fix in `pycdlib-extract-files` at line 100, you can change `iso.get_file_from_iso(relname, **{pathname: ident_to_here})` to `iso.get_file_from_iso(relname[:-2], **{pathname: ident_to_here})`, though I'm not sure if this is something that should (or shouldn't) be changed in the library. Lastly, files that have no extension are given an extra period at the end (before the `;1`). This behavior can be observed using the Ubuntu 18.04.2 LTS install ISO: https://www.ubuntu.com/download/desktop
Now the output looks something like:
```
Opening /mnt/c/Users/P008261C/Downloads/ISOs/ubuntu-18.04.2-desktop-amd64.iso

.DISK
BOOT
CASPER
DISTS
EFI
INSTALL
ISOLINUX
MD5SUM.TXT;1
PICS
POOL
PRESEED
README.DISKDEFINES;1
UBUNTU.;1
ERROR on UBUNTU.;1: Symlinks have no data associated with them
.DISK/BASE_INSTALLABLE.;1
```

**Comment by clalancette** [comment]
This is because `pycdlib-extract-data` extracts the ISO9660 filenames by default.  In original ISO9660, filenames all have to be all-caps, 8.3 files with a semicolcon and version at the end.  If you run the tool like:

```
pycdlib-extract-data -path-type rockridge <path/to/iso>
```

You'll see filenames you are used to.

Like #22, it's not entirely clear to me what to do here, since the ISO could contain ISO9660, RockRidge, Joliet, and UDF (all with different or mirrored contents), and it is unclear what the user wants without them telling us.  From that perspective, it may be best if `-path-type` was a required argument.  What do you think about that?

**Comment by amlamarra** [comment]
I don't really understand ISOs all that well, so maybe... What's the easiest way to determine the ISO type you're working with? Is there any way for `pycdlib-extract-data` to determine that automatically?

**Comment by clalancette** [comment]
There are two different things I can think of:

1.  Add an "auto" mode to `pycdlib-extract-files`, which would first try to extract UDF, then Rock Ridge, then Joliet, and then ISO9660.  This is similar to the way that `mount` works on Linux.  This will do the correct thing in like 90% of the cases; for the ones where there is different, valid data on more than one filesystem, the user could use `-path-type` to do the right thing.

1.  Add a "union" mode to `pycdlib-extract-files`, which would try to extract the files from *all* of the filesystems.  This would ensure you get all of the data out of the ISO, but would lead to some duplicated files and some additional I/O.

What do you think about these options?

**Comment by amlamarra** [comment]
I like the idea of an "auto" mode. Would you have it stop after successfully extracting files from one of the types?

Sorry if I'm getting a little off topic from this issue, but my other recommendation (if you'd have time for it) is to make `pycdlib-extract-files`, and the other tools, more friendly for importing as a module.

**Comment by clalancette** [comment]
> I like the idea of an "auto" mode. Would you have it stop after successfully extracting files from one of the types?

Yeah, that would be the idea.  I'll look at implementing that.

> 
> Sorry if I'm getting a little off topic from this issue, but my other recommendation (if you'd have time for it) is to make `pycdlib-extract-files`, and the other tools, more friendly for importing as a module.

So, the thing about `pycdlib-extract-files` (and all of the tools, really) is that they are meant to be demonstrations of the `PyCdlib` class and its API.  I'm generally expecting people to use the `PyCdlib` API; it's just been convenient for testing and scripting to have the tools around.  I'm happy to enhance the tools, but if you want to do things programmatically, I highly recommend using the `PyCdlib` class.

**Comment by clalancette** [comment]
All right, try out the tip of master (at least commit fd60457ecd56b918807df3bff9d88bcc6b4f4537).  That should implement the 'auto' mode for `pycdlib-extract-files`.  I'll close this out for now, but if you have trouble or it doesn't work for you, feel free to reopen and we can debug.
