### ISSUE TITLE
add_file Error

### ISSUE THREAD

**Issue by padingo** [clalancette/pycdlib#29]
Hello, 
is this the right way to add a new file to the iso?

            iso = pycdlib.PyCdlib()
            iso.new()
            iso.add_file('app/static/file_daten/test.pdf', '/FOO.;1')
            iso.write('app/static/file_daten/test1.iso')
            iso.close()

I get this error message: OSError: [Errno 38] Socket operation on non-socket

**Comment by clalancette** [comment]
Yeah, that code seems reasonable to me, and I think it should work.  A few questions:

1.  Does `app/state/file_daten/test.pdf` definitely exist?  Also, is the path relative to where you launched the script correct?
1.  Does `app/static/file_daten` directory exist for the output?
1.  Any possibility you can share the contents of `test.pdf` with me?  If not, at least detailed file information about it (including the exact file size) would be helpful.

**Comment by padingo** [comment]
Thank you for your quick reply.

To 1 and 2: Yes, the path are are available and definitely exist. If I give a wrong path I get a "FileNotFoundError".

To 3: I tested this with different text files. For example, with a .txt with plain text. Are there any specific requests to the file?

**Comment by clalancette** [comment]
> To 3: I tested this with different text files. For example, with a .txt with plain text. Are there any specific requests to the file?

Hm, no.  In that case, I'm not sure, since simple tests work here for me.  A couple of other things:
1.  What version of pycdlib are you using?
1.  Can you send me the full stack trace when you hit the error?  That might pinpoint it a little more.

**Comment by padingo** [comment]
1. The version is: pycdlib-1.7.0
2. `>>> iso.write(isofile)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/P/myvenv/lib/python3.7/site-packages/pycdlib/pycdlib.py", line 4244, in write
    self._write_fp(fp, blocksize, progress_cb, progress_opaque)
  File "/Users/P/myvenv/lib/python3.7/site-packages/pycdlib/pycdlib.py", line 3074, in _write_fp
    progress.call(self._output_file_data(outfp, blocksize, ino))
  File "/Users/P/myvenv/lib/python3.7/site-packages/pycdlib/pycdlib.py", line 2728, in _output_file_data
    utils.copy_data(data_len, blocksize, data_fp, outfp)
  File "/Users/P/myvenv/lib/python3.7/site-packages/pycdlib/utils.py", line 131, in copy_data
    sendfile(outfp.fileno(), infp.fileno(), in_offset, data_length)
OSError: [Errno 38] Socket operation on non-socket`

**Comment by clalancette** [comment]
Ah, I see, that was the clue I needed.  You are on macOS, which I have never tested against before.  On Linux, I use an API called `sendfile` to speed up copying of data from one file descriptor to another.  There is an API called `sendfile` on macOS which does something similar, but it can only be used for sockets, not general file descriptors.  So in c189205c00a7c9a4ffca52c71a2eb4d8a25c10ba, I changed it so that we use the slower block-copy method on macOS, which I think will fix it for you.  Please give it a whirl and let me know.  I'll close this out for now, but feel free to reopen if it doesn't fix it for you.  Thanks for the bug report!

**Comment by padingo** [comment]
Many thanks for the help! 

With the changes I can create the Iso without problems. Unfortunately, after creating the iso, it does not have the content I've added. 

Do you have an idea what the problem could be?

**Comment by clalancette** [comment]
Hm, not sure what is going on there; in my test on macOS Mojave, I was able to add a single file and write it out, and it showed up on the disk.

Are you using exactly the code you originally posted, or something different?  What version of macOS are you running?

**Comment by padingo** [comment]
Hello, 
below you can find the complete code.
I tried it with Mojave 10.14.6 and Ubuntu. Same Problem.
There is only a file "FOO" in the Iso but not the desired exe file.

`          
import pycdlib

isofile = 'malware_app/static/file_daten/{}.iso'.format(vorlagen.dateiname)

iso = pycdlib.PyCdlib()

iso.new()

iso.add_file('malware_app/static/file_daten/Vorlage_file.exe', '/FOO.;1')

iso.write(isofile)

iso.close()
`

**Comment by clalancette** [comment]
```
import pycdlib

isofile = 'malware_app/static/file_daten/{}.iso'.format(vorlagen.dateiname)

iso = pycdlib.PyCdlib()
iso.new()
iso.add_file('malware_app/static/file_daten/Vorlage_file.exe', '/FOO.;1')
iso.write(isofile)
iso.close()
```

In this example, what you are doing is creating a new ISO and adding a file from local filename `Vorlage_file.exe` to a file called `FOO` on the ISO.  If you wanted to call the file on the ISO to `VORLAGE.EXE`, for instance, you would change the add_file() line above to:

```
iso.add_file('malware_app/static/file_daten/Vorlage_file.exe', '/VORLAGE.EXE;1')
```

Note that with no arguments, pycdlib creates an ISO with only original ISO9660 support, which has very restrictive filenames.  Most likely you want to create the ISO with Rock Ridge or Joliet support (or both); see https://clalancette.github.io/pycdlib/standards.html for some information on what you may want to choose.

**Comment by padingo** [comment]
Many thanks for the help.
Everything works!

**Comment by davguang** [comment]
Can I copy the local directory？
