### ISSUE TITLE
what is this command genisoimage equivalence code

### ISSUE THREAD

**Issue by V0idk** [clalancette/pycdlib#37]
mkisofs -R -J -T -r -l -d -joliet-long -allow-multidot -allow-leading-dots -no-bak -V ”label“ -o 1.iso -e images/efiboot.img -no-emul-boot ./

**Comment by clalancette** [comment]
It's something like:

```
import pycdlib

iso = pycdlib.PyCdlib()
iso.new(interchange_level=3, joliet=3, rock_ridge='1.09', vol_ident='label')
iso.add_directory(iso_path='/IMAGES', rr_name='images', joliet_path='/images')
iso.add_file('/path/to/local/efiboot.img', iso_path='/IMAGES/EFIBOOT.IMG;1', rr_name='efiboot.img', joliet_path='/images/efiboot.img')
iso.add_eltorito(bootfile_path='/IMAGES/EFIBOOT.IMG;1', efi=True)
# Use os.walk() to walk the local directory and iso.add_file() and/or iso.add_directory()
# for all of the other files you want to add;
# see https://github.com/clalancette/pycdlib/blob/95aca81febb82546fca30d5644a286254a4593e4/tools/pycdlib-genisoimage#L716 for a full-featured but complicated way to do it.
iso.write('1.iso')
iso.close()
```

I'll point out that pycdlib doesn't currently support:

* `-T` - This makes a translation table, which is essentially unused nowadays
* `-d` - Omits the trailing dot in ISO9660 filenames
* `-allow-multidot` - Allows multiple dots in ISO9660 filenames
* `-allow-leading-dots` - Allows ISO9660 filenames to start with a dot

The `-T` would be quite some work to add, but possible.  The other three would be very easy to add.

Let me know if this is useful to you.  I'll close this out for now, but feel free to keep commenting here and/or reopen if you need more help.
