### ISSUE TITLE
Is the library ever going to support dvd sized isos?

### ISSUE THREAD

**Issue by i30817** [clalancette/pycdlib#4]
Useful for most ps2 games.

**Comment by clalancette** [comment]
I think you are referring to the UDF specification.  If so, yes, UDF is on the roadmap, but I haven't had time to implement it.  I'm guessing it is going to be quite a bit of work, so it may take a while.

**Comment by clalancette** [comment]
And just to be clear, the library today supports making and parsing very large "standard" ISOs.  I've tested making ISOs up to 16GB, but in theory it should be able to handle much larger ones.

**Comment by i30817** [comment]
Oh, i see. Yes it's quite likely it's another format - i was testing it on ps2 isos.

**Comment by i30817** [comment]
Ok, i tested this out after updating to master with pip and apparently this works very well already. I don't actually know if the isos are UDF or not, but i can extract files and the few i have parse.

A problem for me is that sony decided to make the iso.pvd.system_identifier of ps2 discs the same as ps2 discs. This combined with how both systems serials use the same scheme makes it hard to identify them without a user parameter.
