### ISSUE TITLE
Large file support (>4GB)

### ISSUE THREAD

**Issue by brad-anton** [clalancette/pycdlib#42]
ISO 9660 offers a 32-bit field to describe the file size, which means files greater than 4GB are not supported. Only `actual_filesize - 4294967296` bytes are written when a >=4GB file is extracted with pycdlib. 

This can be clearly seen by adding a `print(data_length_le)` to `dr.py` [after the call to `struct.unpack_from()`](https://github.com/clalancette/pycdlib/blob/master/pycdlib/dr.py#L187-L190)

One [seemingly common solution](https://en.wikipedia.org/wiki/ISO_9660#The_2/4_GiB_file_size_limit) to this is to leverage the multi-extent feature of ISO 9660 level 3.

**Comment by clalancette** [comment]
Thanks for the report.

So the thing is, pycdlib already implements the multi-extent feature.  But I think there may be a bug in it as you point out, as I'm unable to make it work properly right now.  I'll give it a look a little later on, but any additional debugging or pull requests would make it go faster.

**Comment by clalancette** [comment]
Just a further update; after some testing, it looks like pycdlib supports files > 4GB fine, but anything larger than 6GB (or exactly 6442444800 bytes) has the problem you describe.  Still investigating.

**Comment by clalancette** [comment]
All right, I found two separate bugs in the large file extent handling.  I've now fixed them both; it should be possible to deal with large files on master now.

Thanks again for the report, this was very helpful.  Closing this out.
