### ISSUE TITLE
EFI GPT Section

### ISSUE THREAD

**Issue by richard-gravy** [clalancette/pycdlib#44]
Hello,

I am trying to replicate the following in pycdlib:-
`xorrisofs -output out.iso -full-iso9660-filenames -rational-rock -efi-boot-part --efi-boot-image -e boot/grub/efi.img -no-emul-boot .`
There are EFI options for add_eltorito, but none seem to actually create a GPT header in the empty area of the beginning of the ISO.
I have been testing the result against the EFI firmware on qemu.  No combination of options appear to result in a bootable image.
The xorrisofs command produces a bootable image.

Can this be added to pycdlib?

**Comment by clalancette** [comment]
> Can this be added to pycdlib?

I can certainly give it a shot.

Two things that would help me here would be a directory layout that I can actually produce a valid ISO from, and a qemu command-line that I could test with.  Thanks!

**Comment by richard-gravy** [comment]
My test layout is basically the current VM-specific release of Alpine Linux:-
http://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/x86_64/alpine-virt-3.11.3-x86_64.iso
39 MB

On that ISO, /boot/grub/efi.img is a FAT image containing the GRUB bootloader.

Success condition would be booting the output ISO and seeing the GNU GRUB 2.02 screen with its default boot entry highlighted (Linux virt).

Don't usually use qemu from the CLI, usually fire up via virt-manager, but I managed to conjure up a basic command that starts on the Q35 chipset with the TianoCore EFI firmware, loading /tmp/image.iso as the default boot device:-
`/usr/bin/qemu-system-x86_64 -machine pc-q35-4.1 -drive file=/usr/share/edk2/ovmf/OVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on -m 1024 -drive file=/tmp/image.iso,format=raw,if=none,id=drive-sata0-0-0,readonly=on -device ide-cd,bus=ide.0,drive=drive-sata0-0-0,id=sata0-0-0,bootindex=1`

**Comment by clalancette** [comment]
I ended up doing a whole slew of work on EFI support, and landed it on master.  It now seems to do the right thing for alpine linux, though I didn't test it out with the qemu.  Please give it a whirl when you get a chance.  For now, I'm going to close this out.  Thanks for the report.
