### ISSUE TITLE
Truncated file on extraction while processing Windows 10 Installer iso (UDF)

### ISSUE THREAD

**Issue by gergely-kalman** [clalancette/pycdlib#45]
I am trying to rebuild the official Windows 10 Installer .iso to contain autounattend.xml as I found no usable tool for this.

I started by comparing pycdlib extraction with what I get if I mount the iso as udf.

To my surprise this failed, install.wim got truncated to 2147479552, but it should be 4289073755 bytes.

Everything else worked perfectly, sha1 hashes and filenames match, except for this.

Hashes:
Bad: 7b56f5007d482db2d27366bcb915a5c21a16a247  ./sources/install.wim
Good: d0c1c8f09782d4fd4861f22d04ec4ad58a73e414  ./sources/install.wim

Investingating this a bit I found that if I monkey-patch use_sendfile in utils.py copy_data() to always be false, extraction works as expected.
```
    use_sendfile = False  # I added this line
    if use_sendfile:
        # This is one of those instances where using the file object and the
        # file descriptor causes problems.  The sendfile() call actually updates
        # the underlying file descriptor, but the file object does not know
        # about it.  To get around this, we instead get the offset, allow
```

In use_sendfile()
`sendfile(outfp.fileno(), infp.fileno(), in_offset, data_length)`

data_length == 4289073755, which is correct.

sendfile() actually returns the bytes it wrote, which will come up as `2147479552`, but the code doesn't check this.

This makes me think that either sendfile() is bad or infp gets exhausted earlier.

I can upload the iso somewhere, as it seems to be no longer available from Microsoft directly.

SHA1 of iso: 344ca92459c23663d5f857c72a7c030f85f19be8

**Comment by gergely-kalman** [comment]
Nevermind this, using latest master (2abdb50884627f75b5354e29e4656b745c31d5c8) fixed it.

You might want to consider a release, as some people might have had the same problem and last one was 4 months ago.

**Comment by clalancette** [comment]
Thanks for the detailed analysis, you came to the same conclusion I did about `sendfile`.  As you saw, I've now removed its use from pycdlib.

Your idea to make a new release of pycdlib is a good one; I'll probably do one later on this week.
