### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by bootrino** [clalancette/pycdlib#5]
Hello,

If I create an open source application that uses the MIT or Apache license, is my application allowed to import and use pycdlib?  The user of my application would need to install pycdlib as a dependency of course via pip install pycdlib.

thanks

**Comment by clalancette** [comment]
I am definitely not a lawyer, so what I say here can only be termed opinion.  But as far as I know, combining LGPL and MIT is no problem at all (see Wikipedia for another opinion: https://en.wikipedia.org/wiki/License_compatibility).  It seems like Apache 2 and LGPL 2.1 isn't compatible, but Apache 2 and LGPL 3 is, so I would be willing to entertain changing the license of this project to LGPL 3 if that would make your life easier.

**Comment by clalancette** [comment]
I'm going to close this out for now, since I haven't heard back in a while.  Feel free to comment or reopen the issue if you want to discuss licensing further.  Thanks!
