### ISSUE TITLE
PyCdlibInvalidInput('Could not find path')

### ISSUE THREAD

**Issue by willervinNTS** [clalancette/pycdlib#51]
I'm having trouble trying to extract a file from my ISO.
`iso = pycdlib.PyCdlib()`
`iso.open(dst_path)`

`extracted = BytesIO()`
`iso.get_file_from_iso_fp(extracted, iso_path="/KS.CFG;1")`

When i try this I am getting: `pycdlib.pycdlibexception.PyCdlibInvalidInput: Could not find path`

I know this file exists on the ISO because when I do this:
`dir = iso.list_children(iso_path="/")`
`for file in dir:`
    `print(file.file_identifier())`

I see b'KS.CFG' get printed to the console. Any help would be much appreciated

**Comment by clalancette** [comment]
Sorry I didn't get around to look at this earlier.  I suspect that the problem is that the filename is `KS.CFG`, but you were trying to extract `KS.CFG;1`.  If you remove the `;1` at the end, does it work?  If not, can you share an ISO image with me so I can take a look?

**Comment by clalancette** [comment]
No response in over a year, so I'm going to close this out.  If you are still having problems, feel free to reopen the issue.
