### ISSUE TITLE
ISO Level 4 and Directory Depth

### ISSUE THREAD

**Issue by zebulon501** [clalancette/pycdlib#52]
`pycdlib-genisoimage` complains if the directory structure is too deep even with `-iso-level 4`.

It seems the test in `pycdlib/pycdlib/pycdlib.py:3218` shall only be done if the  `interchange_level` is lower than `4`. It seems to do the job, but due to the complexity of the code, it might have unexpected side effects.

**Comment by clalancette** [comment]
Nice catch.  You are absolutely right about the problem, and the solution.  In https://github.com/clalancette/pycdlib/commit/01b4168e5df722949e6b3eb2e15cab415c5d1c97 , I made the fix you suggested and also added a test for that particular case.  It seems to work for me now, so I'm going to go ahead and close this.  Please test it out when you get a chance and let me know how it goes for you.
