### ISSUE TITLE
Distribute wheels on PyPi

### ISSUE THREAD

**Issue by clebergnu** [clalancette/pycdlib#53]
Hi,

The QEMU project uses pycdlib, and usually installs them from pip.  We could benefit from having pycdlib also being distributed in wheels, so that the installation is quicker and possible on more constrained environments.

A pointer to one of the reasons that motivate this can be seen at:

https://bugs.launchpad.net/qemu/+bug/1897783

**Comment by clalancette** [comment]
I'm not opposed at all to doing it, its just that nobody has asked before :).

I'm about due for another release anyway, so when I do the new release I'll also upload a wheel for it.  I'm hoping to get to it tomorrow, but if not, it will be early next week.

**Comment by clebergnu** [comment]
Much appreciated @clalancette !

**Comment by clalancette** [comment]
I just did a 1.11.0 release, and in theory I also uploaded a wheel for it.  I'm going to close this out, assuming that works, but please give it a try and let me know how it goes for you.

**Comment by clebergnu** [comment]
Thank you @clalancette !
