### ISSUE TITLE
pycdlib.pycdlibexception.PyCdlibInvalidISO: Unknown SUSP record

### ISSUE THREAD

**Issue by keeely** [clalancette/pycdlib#54]
```
$ wget https://ftp.gwdg.de/pub/linux/mx/iso/ANTIX/Final/antiX-19/antiX-19.2.1_x64-base.iso
$ python3
Python 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycdlib
>>> iso = pycdlib.PyCdlib()
>>> iso.open("antiX-19.2.1_x64-base.iso")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pycdlib/pycdlib.py", line 4170, in open
    self._open_fp(fp)
  File "/usr/local/lib/python3.8/site-packages/pycdlib/pycdlib.py", line 2380, in _open_fp
    ic_level, lastbyte = self._walk_directories(self.pvd, extent_to_ptr,
  File "/usr/local/lib/python3.8/site-packages/pycdlib/pycdlib.py", line 1165, in _walk_directories
    new_record.rock_ridge.parse(con_block, False,
  File "/usr/local/lib/python3.8/site-packages/pycdlib/rockridge.py", line 2318, in parse
    raise pycdlibexception.PyCdlibInvalidISO('Unknown SUSP record')
pycdlib.pycdlibexception.PyCdlibInvalidISO: Unknown SUSP record
>>>  exit
$ pip3 list | grep pycdlib
pycdlib                               1.10.0
```

AntiX can also be dowloaded from any of the [mirrors](https://antixlinux.com/download/).

**Comment by clalancette** [comment]
Thanks for the report.  It looks like the `AL` record is an unofficial extension by libisofs: https://dev.lovelyhq.com/libburnia/libisofs/src/branch/master/doc/susp_aaip_2_0.txt .  Since it doesn't collide with any of the other extensions, I see no reason not to support it in pycdlib.  It will take me a bit of time to implement it, though.

**Comment by keeely** [comment]
If it's going to take significant time for you and nobody else wants it, don't worry.  I may be able to do what I want using xorriso so I'm going to try that route in the meantime.

**Comment by clalancette** [comment]
> If it's going to take significant time for you and nobody else wants it, don't worry. I may be able to do what I want using xorriso so I'm going to try that route in the meantime.

I want to try to make pycdlib as compatible as possible, so I'll go ahead and implement it.  Hopefully in the next few days, but no promises.

**Comment by clalancette** [comment]
All right.  I've done an initial implementation of the AL record now.  It isn't 100% complete; in particular, there is currently no way for a user to add attributes while creating a new file.  However, the current implementation is good enough to accept (and preserve) the record, and the backend code to add new attributes is all there.

@keeely please give it a try when you get a chance.  It seems to work fine for me with the AntiX ISOs in your initial description.  I'm going to close this out, but please feel free to keep commenting or reopen if it still doesn't work for you.
