### ISSUE TITLE
Export ISO files to Directory

### ISSUE THREAD

**Issue by JasonKramer525** [clalancette/pycdlib#56]
Is there any way to extract an existing ISO and save it to a directory? Currently, I am able to open up the existing ISO using pycdlib and list the files using file_identifier(), but is there a way to save individual files or all of the files in a directory? Thank you in advance!

**Comment by JasonKramer525** [comment]
I'm now using get_and_write to save the extracted iso files. My current issue is that I am trying to recursively run through the iso files, but I cannot tell what is a folder and what isn't. Is there a way to get the file types from pycdlib?

**Comment by JasonKramer525** [comment]
Was able to solve this again by using the walk function. Thank you for including that! No need to make it recursive with walk! Is there an even easier way to save the files or was my method the best way?

**Comment by clalancette** [comment]
It looks like you've figured it out.  Indeed, `iso.walk` is the easiest way to recurse through all of the files on the ISO and extract them all.  The example for using it is [here](https://github.com/clalancette/pycdlib/blob/master/tools/pycdlib-extract-files), if you haven't found it already.  For a slightly more "manual" way to do it, take a look at https://github.com/clalancette/pycdlib/blob/master/tools/pycdlib-extract-files (this tool was written before I implemented `iso.walk`).

Either way, it looks like you've solved your problem.  I'm going to go ahead and close this, but please feel free to keep commenting or open other issues as you find them.  And thanks for using it!
