### ISSUE TITLE
Parsing MagicISO files

### ISSUE THREAD

**Issue by MugurAnghel** [clalancette/pycdlib#67]
I have noticed that images created with MagicISO are not parsed by pycdlib because they dont fully respect the Ecma-119 spec. More specifically the Volume Descriptor Date is missing the 2 bytes for hundredths of second (they are not actually missing, but they are null).
This in turn causes a hard failure in parsing the ISO image, because pycdlib tries to convert the 2 null bytes into an integer and ends up throwing an exception.
While pycdlib is following the specification, these specific images are still "valid", can be extracted and are otherwise functional with other apps. 
I would suggest encasing the date parsing part in a try/catch statement and default to zero where needed.

**Comment by clalancette** [comment]
I've just fixed this one with 220365821d3607ec72167892587819dce9c35768 and a try/except as you suggested.  Thanks for the bug report!

**Comment by MugurAnghel** [comment]
Awesome! Thank you!
