### ISSUE TITLE
isohybrid mastered with pycdlib won't boot as usb stick, same content mastered with xorriso boots fine

### ISSUE THREAD

**Issue by sraustein** [clalancette/pycdlib#68]
Mastering a hybrid ISO image consisting of just ISOLINUX and the base TinyCoreLinux produces an image which boots fine as a normal El Torito ISO boot but fails with the dreaded `isolinux.bin missing or corrupt` error; mastering the exact same content with xorriso works fine.  Original problem occurred in a complex $dayjob thing I can't share, but problem is easily reproducible with just a basic TinyCoreLinux image.

Example ISO images:
* <https://www.hactrn.net/opaque/pycdlib-hybrid-issue/pycdlib-hybrid-broken.iso>
* <https://www.hactrn.net/opaque/pycdlib-hybrid-issue/xorriso-hybrid-working.iso>

I've attached two scripts that I used for testing this, all testing done on Debian (9 or 10, same behavior)
1. First attached script generates the example images (requires `xorriso`, `isolinux`, and `syslinux-common`)
2. Second attached script attempts to boot an image on a temporary libvirt VM (requires `libvirt-daemon` and `libvirt-clients`).

I did note one odd thing about pycdlib's isohybrid code: it seems to contain an embedded copy of (most of) ISOLINUX's `isohdpfx.bin` boot block: given that the ISOLINUX documentation says this boot block is closely tied to the specific version of ISOLINUX, it might be better to allow some way for the user to pass in the desired copy of this boot block.  But I'm pretty sure that's not the only problem, I tried just updating the embedded copy to match the current version of `isohdpfx.bin` and it didn't change the (visible) behavior.

Thanks for an awesome library.  Hope this is enough to nail down the problem.  Happy to answer any questions.

[build-images.py.gz](https://github.com/clalancette/pycdlib/files/6722083/build-images.py.gz)
[test-images-libvirt.py.gz](https://github.com/clalancette/pycdlib/files/6722084/test-images-libvirt.py.gz)

**Comment by sraustein** [comment]
One additional datapoint: post-processing the non-booting (in isohybrid mode) pycdlib-generated .iso with the `isohybrid.pl` script that ships with SYSLINUX (`syslinux-utils` package on Debian) seems to fix the problem.

**Comment by sraustein** [comment]
Found it.  ISOLINUX expects the `rba` value to be scaled by a factor of four.

**Comment by clalancette** [comment]
It looks like this was fixed by #69, so closing.  Thanks for the report and the fix.
