### ISSUE TITLE
Header only read support

### ISSUE THREAD

**Issue by Nicba1010** [clalancette/pycdlib#8]
Is there a possibilty to have this support reading the header of the iso only?

**Comment by clalancette** [comment]
Potentially, though it's unclear which headers we would parse (PVD, Joliet, Boot Records, UDF, etc?).  What are you trying to accomplish that the current "parse all the metadata" doesn't do?

**Comment by Nicba1010** [comment]
Ah sorry I did not see that function. I am making a PS3 iso toolset in python btw.

**Comment by clalancette** [comment]
Great.  Please give it a try and let me know if you have any problems (preferably in new issues).  I'm going to close this out for now.  Thanks!
