### ISSUE TITLE
Type hinting

### ISSUE THREAD

**Issue by Nicba1010** [clalancette/pycdlib#9]
Are there any plans for type hinting and if I were to submit a PR for that would it be accepted?

**Comment by clalancette** [comment]
The main problem with type-hinting would be backwards compatibility.  Right now the library supports both python2 and python3, and I'd like to keep it that way.  Is there a way to add type-hinting that is backwards compatible?

**Comment by Nicba1010** [comment]
Unfortunatelly not, thank you for answering :)
